/**
 * Chunk 2 — Process-clean gate tests (F-61, AC 2).
 *
 * The gate (`scanDiffForProcessLanguage`) must:
 *   - Pass a diff that contains no factory-internal patterns.
 *   - Refuse a diff that contains any pattern from PROCESS_CLEAN_PATTERNS,
 *     naming the offending file:line.
 *   - Ignore removed lines (prefixed '-') — they are leaving the tree.
 *   - Return all offending locations (not just the first).
 *   - Be deterministic (same diff → same result every call).
 *   - Not treat context lines as clean when they hit a pattern.
 *
 * These are pure function tests — no git subprocess, no disk I/O.
 */

import { describe, it, expect } from 'vitest';
import {
  scanDiffForProcessLanguage,
  PROCESS_CLEAN_PATTERNS,
} from '../../src/engine/process-clean.js';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Build a minimal unified diff string for a single file change. */
function makeDiff(fileName: string, addedLines: string[], removedLines: string[] = []): string {
  const lines: string[] = [
    `diff --git a/${fileName} b/${fileName}`,
    `--- a/${fileName}`,
    `+++ b/${fileName}`,
    '@@ -1,3 +1,3 @@',
    ...removedLines.map((l) => `-${l}`),
    ...addedLines.map((l) => `+${l}`),
  ];
  return lines.join('\n');
}

/** Build a diff with context lines (no +/- prefix). */
function makeDiffWithContext(fileName: string, contextLines: string[]): string {
  return [
    `diff --git a/${fileName} b/${fileName}`,
    `--- a/${fileName}`,
    `+++ b/${fileName}`,
    '@@ -1,3 +1,3 @@',
    ...contextLines,
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Clean diffs — must pass
// ---------------------------------------------------------------------------

describe('scanDiffForProcessLanguage — clean diffs', () => {
  it('passes an empty diff', () => {
    const result = scanDiffForProcessLanguage('');
    expect(result.ok).toBe(true);
  });

  it('passes a diff with normal source code on added lines', () => {
    const diff = makeDiff('src/index.ts', [
      "export function greet(name: string): string {",
      "  return `Hello, ${name}!`;",
      "}",
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(true);
  });

  it('passes a diff with normal prose in a markdown file', () => {
    const diff = makeDiff('CHANGELOG.md', [
      '## v0.2.0',
      '- Added greeting utility',
      '- Fixed type errors in parser',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(true);
  });

  it('passes a diff that has factory-pattern strings only on removed lines', () => {
    // Removed lines leave the tree — they must not trigger the gate.
    const diff = makeDiff(
      'src/index.ts',
      ['export const version = "2";'],   // added — clean
      [
        'tree/',                           // removed — should be ignored
        'goalid: foo',                    // removed — should be ignored
        'improve-factory reference',      // removed — should be ignored
      ],
    );
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Dirty diffs — must refuse and name offending file:line
// ---------------------------------------------------------------------------

describe('scanDiffForProcessLanguage — dirty diffs', () => {
  it('refuses a diff that contains "tree/" on an added line', () => {
    const diff = makeDiff('src/util.ts', [
      '// See tree/abc123 for context',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.offenses.length).toBeGreaterThan(0);
      expect(result.offenses[0]).toContain('src/util.ts');
    }
  });

  it('refuses a diff containing "goalid"', () => {
    const diff = makeDiff('src/config.ts', [
      'const goalId = "g-abc-123";',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('refuses a diff containing "improve-factory"', () => {
    const diff = makeDiff('README.md', [
      'This PR was generated by the improve-factory workflow.',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('refuses a diff containing "corellia"', () => {
    const diff = makeDiff('docs/notes.md', [
      'Corellia is the factory repo.',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('refuses a diff containing "docs/iterations"', () => {
    const diff = makeDiff('src/readme.ts', [
      '// See docs/iterations/06-loop for context',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('refuses a diff containing ".corellia/worktrees"', () => {
    const diff = makeDiff('package.json', [
      '"workspacePath": ".corellia/worktrees/my-tree"',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('refuses a diff containing ".claude/worktrees"', () => {
    const diff = makeDiff('package.json', [
      '"workspacePath": ".claude/worktrees/my-tree"',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('refuses a diff containing "build-plan"', () => {
    const diff = makeDiff('NOTES.md', [
      '# build-plan for iteration 6',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('reports the correct filename in the offense', () => {
    const diff = makeDiff('lib/helper.ts', [
      '// tree/my-tree',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.offenses[0]).toContain('lib/helper.ts');
    }
  });

  it('reports a line number in the offense', () => {
    const diff = makeDiff('src/x.ts', ['tree/abc']);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      // Offense format: "<file>:<lineNo>: <text>"
      expect(result.offenses[0]).toMatch(/:\d+:/);
    }
  });

  it('reports ALL offending lines, not just the first', () => {
    const diff = makeDiff('src/x.ts', [
      '// tree/abc',
      'const goalId = "g1";',
      '// improve-factory reference',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.offenses.length).toBeGreaterThanOrEqual(3);
    }
  });

  it('is case-insensitive for pattern matching', () => {
    // "CORELLIA" should match "corellia" pattern.
    const diff = makeDiff('src/a.ts', ['// CORELLIA repo reference']);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });

  it('refuses context lines that contain a pattern', () => {
    // Context lines (no prefix) should also be scanned.
    const diff = makeDiffWithContext('src/ctx.ts', [
      ' normal context line',
      ' another context line with tree/ reference',
    ]);
    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Multi-file diffs — file tracking
// ---------------------------------------------------------------------------

describe('scanDiffForProcessLanguage — multi-file diffs', () => {
  it('attributes offenses to the correct file in a multi-file diff', () => {
    const diff = [
      'diff --git a/clean.ts b/clean.ts',
      '--- a/clean.ts',
      '+++ b/clean.ts',
      '@@ -1,1 +1,1 @@',
      '+export const x = 1;',
      'diff --git a/dirty.ts b/dirty.ts',
      '--- a/dirty.ts',
      '+++ b/dirty.ts',
      '@@ -1,1 +1,1 @@',
      '+// goalid: g-abc',
    ].join('\n');

    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(false);
    if (!result.ok) {
      expect(result.offenses.length).toBe(1);
      expect(result.offenses[0]).toContain('dirty.ts');
      expect(result.offenses[0]).not.toContain('clean.ts');
    }
  });

  it('passes a two-file diff that is fully clean', () => {
    const diff = [
      'diff --git a/a.ts b/a.ts',
      '--- a/a.ts',
      '+++ b/a.ts',
      '@@ -1 +1 @@',
      '+const a = 1;',
      'diff --git a/b.ts b/b.ts',
      '--- a/b.ts',
      '+++ b/b.ts',
      '@@ -1 +1 @@',
      '+const b = 2;',
    ].join('\n');

    const result = scanDiffForProcessLanguage(diff);
    expect(result.ok).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// PROCESS_CLEAN_PATTERNS export — verify the contract
// ---------------------------------------------------------------------------

describe('PROCESS_CLEAN_PATTERNS', () => {
  it('is a non-empty readonly array', () => {
    expect(Array.isArray(PROCESS_CLEAN_PATTERNS)).toBe(true);
    expect(PROCESS_CLEAN_PATTERNS.length).toBeGreaterThan(0);
  });

  it('contains "tree/"', () => {
    expect(PROCESS_CLEAN_PATTERNS).toContain('tree/');
  });

  it('contains "improve-factory"', () => {
    expect(PROCESS_CLEAN_PATTERNS).toContain('improve-factory');
  });

  it('contains "goalid"', () => {
    expect(PROCESS_CLEAN_PATTERNS).toContain('goalid');
  });

  it('contains "corellia"', () => {
    expect(PROCESS_CLEAN_PATTERNS).toContain('corellia');
  });

  it('is deterministic (same array every import)', () => {
    // The exported constant must not change across calls — it's a module-level const.
    const first = [...PROCESS_CLEAN_PATTERNS];
    const second = [...PROCESS_CLEAN_PATTERNS];
    expect(first).toEqual(second);
  });
});
